use crate::llm::models::{DataSource, MessagePart, Role};
use serde_json::{Value, json};

use super::payload_formatter::PayloadFormatter;

/// Builder for constructing OpenAI-compatible message arrays from the
/// internal conversation model.  Separated from the client to keep the
/// message serialisation logic independently testable.
pub struct MessageBuilder<'a> {
    pub formatter: &'a dyn PayloadFormatter,
    pub model: &'a str,
    pub system_prompt: Option<String>,
    pub conversation: &'a [crate::llm::models::Message],
    pub pending_data: &'a [DataSource],
}

impl<'a> MessageBuilder<'a> {
    pub fn build(&self) -> Vec<Value> {
        let mut messages = Vec::new();

        // 1. Mandatory System Prompt (with Date)
        if let Some(ref sp) = self.system_prompt {
            messages.push(json!({"role": "system", "content": sp}));
        }

        let mut processed_messages = Vec::new();
        // Keep track of Tool IDs generated by the assistant to validate subsequent Tool responses.
        let mut available_tool_calls = std::collections::HashSet::new();

        for m in self.conversation {
            match m.role {
                Role::System => {
                    let text = m.get_text(true);
                    if !text.is_empty() {
                        processed_messages.push(json!({
                            "role": "system",
                            "content": text
                        }));
                    }
                }
                Role::Tool => {
                    let mut tool_contents = Vec::new();
                    for part in &m.parts {
                        if let MessagePart::Part(cp) = part
                            && let Some(fr) = &cp.function_response
                        {
                            let content = match fr.get("response") {
                                Some(Value::String(s)) => s.clone(),
                                Some(v) => v.to_string(),
                                None => "".to_string(),
                            };
                            let id = fr.get("id").and_then(|v| v.as_str()).unwrap_or("");
                            let tool_name =
                                fr.get("name").and_then(|v| v.as_str()).unwrap_or("tool");

                            if !id.is_empty() && available_tool_calls.contains(id) {
                                // Anthropic/OpenRouter/Bedrock style: specific tool_call_id in a role:tool message.
                                processed_messages.push(json!({
                                    "role": "tool",
                                    "tool_call_id": id,
                                    "name": tool_name,
                                    "content": content
                                }));
                            } else {
                                // Orphaned or fallback
                                tool_contents
                                    .push(format!("Tool Result ({}): {}", tool_name, content));
                            }
                        }
                    }
                    if !tool_contents.is_empty() {
                        processed_messages.push(json!({
                            "role": "user",
                            "content": tool_contents.join("\n\n")
                        }));
                    }
                }
                _ => {
                    let role = if m.role == Role::Assistant || m.role == Role::Model {
                        "assistant"
                    } else {
                        "user"
                    };

                    // If this is an assistant message, it defines the set of valid tool_call_ids
                    // that the *next* tool messages can use.
                    if role == "assistant" {
                        available_tool_calls.clear();
                    }

                    let mut parts = Vec::new();
                    let mut tool_calls = Vec::new();

                    for part in &m.parts {
                        match part {
                            MessagePart::Text(t) => parts.push(self.formatter.format_text(t)),
                            MessagePart::Part(cp) => {
                                if let Some(t) = &cp.text {
                                    parts.push(self.formatter.format_text(t));
                                }
                                if let Some(fc) = &cp.function_call {
                                    let id = fc.get("id").and_then(|v| v.as_str()).unwrap_or("");
                                    if role == "assistant" && !id.is_empty() {
                                        available_tool_calls.insert(id.to_string());
                                    }

                                    tool_calls.push(json!({
                                        "id": id,
                                        "type": "function",
                                        "function": {
                                            "name": fc.get("name").and_then(|v| v.as_str()).unwrap_or(""),
                                            "arguments": fc.get("arguments").cloned().unwrap_or(json!({})).to_string()
                                        }
                                    }));
                                }
                                if let Some(id) = &cp.inline_data {
                                    let mime =
                                        id.get("mimeType").and_then(|v| v.as_str()).unwrap_or("");
                                    let b64 = id.get("data").and_then(|v| v.as_str()).unwrap_or("");
                                    if mime == "application/pdf" {
                                        if let Some(v) = self.formatter.format_pdf(
                                            b64,
                                            id.get("filename").and_then(|v| v.as_str()),
                                        ) {
                                            parts.push(v);
                                        }
                                    } else if mime.starts_with("image/") {
                                        parts.push(self.formatter.format_image(mime, b64));
                                    } else if mime.starts_with("audio/") {
                                        parts.push(self.formatter.format_audio(mime, b64));
                                    }
                                }
                            }
                        }
                    }
                    let content_value = if parts.is_empty() {
                        Value::String("".to_string())
                    } else if parts.len() == 1 && parts[0]["type"] == "text" {
                        parts[0]["text"].clone()
                    } else {
                        Value::Array(parts)
                    };

                    let mut msg = json!({
                        "role": role,
                        "content": content_value,
                    });

                    if !tool_calls.is_empty() {
                        msg["tool_calls"] = Value::Array(tool_calls);
                        // Some providers (like Amazon Bedrock via OpenRouter/Nova) fail if 'content' is an empty string
                        // when 'tool_calls' is present. Others like Arcee AI require it to be present.
                        if role == "assistant"
                            && (content_value == Value::String("".to_string())
                                || content_value == Value::Array(vec![]))
                        {
                            let model_lower = self.model.to_lowercase();
                            if model_lower.contains("nova")
                                && let Some(obj) = msg.as_object_mut()
                            {
                                obj.remove("content");
                            }
                        }
                    }
                    processed_messages.push(msg);
                }
            }
        }

        // Current pending data
        let mut current_parts = Vec::new();
        for d in self.pending_data {
            if d.content_type == "text/plain" {
                current_parts.push(self.formatter.format_text(d.content.as_str().unwrap_or("")));
            } else if d.content_type == "application/pdf" {
                if let Some(v) = self.formatter.format_pdf(
                    d.content.as_str().unwrap_or(""),
                    d.metadata.get("filename").and_then(|v| v.as_str()),
                ) {
                    current_parts.push(v);
                }
            } else if d.content_type.starts_with("image/") {
                current_parts.push(
                    self.formatter
                        .format_image(&d.content_type, d.content.as_str().unwrap_or("")),
                );
            }
        }
        if !current_parts.is_empty() {
            processed_messages.push(json!({"role": "user", "content": if current_parts.len() == 1 && current_parts[0]["type"] == "text" { current_parts[0]["text"].clone() } else { Value::Array(current_parts) }}));
        }

        messages.extend(processed_messages);
        messages
    }
}
